# 拉勾网数据清洗及统计

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
#批量读取文件, os模块获取文件列表
os.listdir('lagou_copy')

['zhengzhou.csv',
 'xiamen.csv',
 '修改记录.txt',
 'foshan.csv',
 '.DS_Store',
 'xian.csv',
 'changsha.csv',
 'wuhan.csv',
 'shenzhen.csv',
 'hangzhou.csv',
 'suzhou.csv',
 'guangzhou.csv',
 'chongqing.csv',
 'chengdu.csv',
 'shanghai.csv',
 'beijing.csv',
 'nanjing.csv',
 'tianjin.csv']

In [4]:
filename_list = []
for filename in os.listdir('lagou_copy'):
#     print(filename)
    #只要csv文件
    if(filename.split('.')[-1] == 'csv'):
        print(filename)
        filename_list.append(filename)

zhengzhou.csv
xiamen.csv
foshan.csv
xian.csv
changsha.csv
wuhan.csv
shenzhen.csv
hangzhou.csv
suzhou.csv
guangzhou.csv
chongqing.csv
chengdu.csv
shanghai.csv
beijing.csv
nanjing.csv
tianjin.csv

In [5]:
filename_list

['zhengzhou.csv',
 'xiamen.csv',
 'foshan.csv',
 'xian.csv',
 'changsha.csv',
 'wuhan.csv',
 'shenzhen.csv',
 'hangzhou.csv',
 'suzhou.csv',
 'guangzhou.csv',
 'chongqing.csv',
 'chengdu.csv',
 'shanghai.csv',
 'beijing.csv',
 'nanjing.csv',
 'tianjin.csv']

In [6]:
#批量读取,城市名作为key,数据作为value

lagou_dict = {}
for filename in filename_list:
    lagou_dict[filename.split('.')[0]] = pd.read_csv('lagou_copy/'+ filename)
print(lagou_dict)

{'zhengzhou':    Unnamed: 0                标题  城市     公司地点     薪资待遇                  工位要求  \
0           0              数据分析  郑州    [北林路]    6k-8k     6k-8k 经验1-3年 / 大专
1           1     数据分析（互联网运营中心）  郑州    [高新区]  12k-24k   12k-24k 经验3-5年 / 本科
2           2        商业化-数据分析经理  郑州    [金水区]  15k-25k   15k-25k 经验3-5年 / 本科
3           3             数据分析师  郑州    [北林路]    4k-8k     4k-8k 经验1-3年 / 本科
4           4            大数据分析师  郑州  [管城回族区]  30k-40k  30k-40k 经验5-10年 / 不限
5           5           金融数据分析师  郑州    [金水区]   6k-10k      6k-10k 经验不限 / 大专
6           6  大数据分析开发工程师助理/实习生  郑州    [经开区]    4k-6k       4k-6k 经验不限 / 大专
7           7            大数据分析师  郑州    [高新区]  15k-25k   15k-25k 经验3-5年 / 本科
8           8          政企大数据分析师  郑州    [高新区]  10k-20k  10k-20k 经验应届毕业生 / 本科

             公司名称                           公司级别  \
0            卓影科技           其他 / 上市公司 / 150-500人
1      中移在线服务有限公司        移动互联网 / 不需要融资 / 2000人以上
2            字节跳动           文娱丨内容 / C轮 / 2000人以上
3  戎易商智（北京）科技有限公司      移动互联网,数据服务 / 未融资 / 15-50人
4            宇通客车          企业服务 / 上市公司 / 2000人以上
5    河南千山教育科技有限公司             金融 / 未融资 / 50-150人
6          缓冲网络科技  移动互联网,人工智能 / 上市公司 / 500-2000人
7      中移在线服务有限公司        移动互联网 / 不需要融资 / 2000人以上
8      中移在线服务有限公司        移动互联网 / 不需要融资 / 2000人以上

                           岗位技能                   公司短评
0                          数据运营  “五险一金、带薪年假、节日福利、加班补助”
1                  教育 数据挖掘 数据分析      “领导好,扁平化,福利多,空间大”
2                          数据分析    “六险一金，餐补，租房补贴，带薪休假”
3       通信/网络设备 移动互联网 SPSS 数据分析       “周末双休，五险一金，带薪年假”
4                  BI SPSS 数据分析          “高薪、福利待遇、假期多”
5                    证券 股票 证券分析       “薪资待遇：8K~10K 双休”
6  工具软件 移动互联网 数据挖掘 数据架构 数据仓库 算法             “包住，发展前景大”
7                      数据分析 SQL      “海量数据 优质平台 发展空间大”
8  分类信息 大数据 数据挖掘 数据架构 数据仓库 数据分析           “六险两金、扁平化管理”  , 'xiamen':     Unnamed: 0             标题  城市    公司地点     薪资待遇                 工位要求  \
0            0          数据分析师  厦门  [前埔医院]   8k-15k   8k-15k 经验1-3年 / 本科
1            1          数据分析师  厦门   [思明区]  10k-20k  10k-20k 经验3-5年 / 本科
2            2        资深数据分析师  厦门   [思明区]  14k-22k  14k-22k 经验3-5年 / 本科
3            3        高级数据分析师  厦门   [思明区]  18k-28k  18k-28k 经验3-5年 / 本科
4            4        高级数据分析师  厦门   [思明区]  20k-40k  20k-40k 经验3-5年 / 本科
5            5        数据分析应用岗  厦门  [湖滨北路]  15k-25k  15k-25k 经验3-5年 / 本科
6            6          数据分析师  厦门   [思明区]   8k-16k   8k-16k 经验1-3年 / 本科
7            7          数据分析师  厦门    [塘边]  10k-14k  10k-14k 经验3-5年 / 本科
8            8      数据开发/数据分析  厦门    [厦港]   6k-12k   6k-12k 经验1-3年 / 大专
9            9  软件开发工程师（数据分析）  厦门   [集美区]    6k-8k    6k-8k 经验1-3年 / 本科
10          10   大数据分析工程师（厦门）  厦门   [思明区]   8k-16k     8k-16k 经验不限 / 本科
11          11  运营（数据分析+投放运营）  厦门   [思明区]    4k-5k    4k-5k 经验1-3年 / 大专
12          12    Python 数据分析  厦门   [思明区]  10k-20k  10k-20k 经验1-3年 / 本科
13          13     开发经理（数据分析）  厦门   [集美区]  10k-15k  10k-15k 经验3-5年 / 本科

     公司名称                          公司级别                       岗位技能  \
0    游动网络          游戏 / 上市公司 / 150-500人                游戏 数据分析 数据库
1    点触科技          游戏 / 上市公司 / 150-500人            数据分析 数据挖掘 MySQL
2      美柚     移动互联网 / D轮及以上 / 500-2000人            SQL BI 数据库 数据分析
3    美图公司           硬件 / 上市公司 / 2000人以上      MySQL 数据分析 Java Scala
4    美团点评         消费生活 / 上市公司 / 2000人以上                       数据分析
5    厦门银行          金融 / 不需要融资 / 2000人以上                     大数据 征信
6    多快好省          金融 / 不需要融资 / 50-150人             互联网金融 数据分析 数据库
7    厦门巨龙  信息安全,数据服务 / 不需要融资 / 150-500人                   数据分析 数据库
8   侠侣亲子游      电商,旅游 / 不需要融资 / 150-500人         本地生活 大数据 数据分析 数据挖掘
9    福建天闻        数据服务,教育 / 未融资 / 15-50人                        大数据
10   美亚柏科    信息安全,数据服务 / 上市公司 / 2000人以上                   Java NLP
11   博格网络           移动互联网 / A轮 / 15-50人                    运营 数据分析
12    金投缘    移动互联网,金融 / 不需要融资 / 50-150人  物流 医疗健康 数据挖掘 数据分析 数据仓库 算法
13   福建天闻        数据服务,教育 / 未融资 / 15-50人                        大数据

                      公司短评
0    “项目奖金，国外旅游，五险一金，年终双薪”
1    “免费班车 免费早餐 免费体检 五险一金”
2            “发展空间大,团队协作好”
3         “弹性工作,海外团队,海外市场”
4           “发展空间大，工作氛围轻松”
5    “扁平管理,绩效奖金,定期体检,管理规范”
6   “弹性上班，周末双休，五险一金 免费午晚餐”
7      “行业潜力大，竞争力薪资，扁平化管理”
8    “带薪假期，免费茶点、员工活动、年度旅游”
9              “五险一金、带薪年假”
10           “五险一金 每年多次调薪”
11      “福利待遇佳,享有提成,发展空间大”
12              “扁平化、广阔前景”
13   “五险一金、带薪年假、绩效奖金、通讯补贴”  , 'foshan':    Unnamed: 0                标题  城市   公司地点     薪资待遇                  工位要求  \
0           0             数据分析师  佛山  [顺德区]   8k-15k   8k-15k 经验5-10年 / 本科
1           1             数据分析师  佛山  [顺德区]   8k-13k    8k-13k 经验3-5年 / 本科
2           2  数据分析资深专家（数据分析经理）  佛山   [桂城]  25k-40k  25k-40k 经验5-10年 / 本科
3           3            大数据分析师  佛山  [顺德区]  20k-30k     20k-30k 经验不限 / 硕士
4           4              数据分析  佛山  [顺德区]    4k-8k       4k-8k 经验不限 / 本科
5           5          大数据分析工程师  佛山  [顺德区]  18k-35k   18k-35k 经验3-5年 / 本科
6           6        产品经理/数据分析师  佛山  [顺德区]   8k-15k   8k-15k 经验5-10年 / 本科
7           7            数据分析专员  佛山  [顺德区]  10k-14k   10k-14k 经验1-3年 / 本科
8           8           高级数据分析师  佛山  [顺德区]  25k-50k  25k-50k 经验5-10年 / 本科
9           9           零售数据分析师  佛山  [顺德区]   8k-15k    8k-15k 经验1年以下 / 本科

           公司名称                         公司级别                      岗位技能  \
0  碧桂园集团数字化管理中心  数据服务,房产家居 / 不需要融资 / 2000人以上                 数据分析 数据运营
1          美的电商          电商 / 上市公司 / 2000人以上  电商 大数据 数据分析 数据运营 SPSS 商业
2     广发银行信用卡中心         金融 / 不需要融资 / 2000人以上   大数据 金融 商业 数据分析 可视化 数据运营
3          融山科技        金融 / 不需要融资 / 150-500人              数据挖掘 数据分析 算法
4            小捷          电商 / 未融资 / 150-500人             电商 移动互联网 SPSS
5        美的集团IT          硬件 / 上市公司 / 2000人以上                  大数据 数据分析
6  碧桂园集团数字化管理中心  数据服务,房产家居 / 不需要融资 / 2000人以上       数据分析 产品设计 产品策划 交互设计
7          美的电商          电商 / 上市公司 / 2000人以上       移动互联网 数据分析 SQL SPSS
8  碧桂园集团数字化管理中心  数据服务,房产家居 / 不需要融资 / 2000人以上                 数据分析 数据处理
9  碧桂园集团数字化管理中心  数据服务,房产家居 / 不需要融资 / 2000人以上                  数据分析 SQL

                     公司短评
0            “500强企业 发展好”
1       “不打卡 团队年轻 领导nice”
2   “个性化推荐， 产品策略，模型，业务分析”
3      “大平台,内部资源,空间大,提成高”
4  “五险一金 平台不小 生日福利 免费观影券”
5    “六险一金,餐补,节日福利,免费健身房”
6              “世界500强企业”
7       “不打卡 团队年轻 领导nice”
8            “500强企业，发展好”
9            “500强企业 发展好”  , 'xian':     Unnamed: 0                      标题  城市      公司地点     薪资待遇  \
0            0                   数据分析师  西安     [莲湖区]    4k-7k
1            1                   数据分析员  西安     [雁塔区]    4k-8k
2            2                 数据分析工程师  西安    [曲江新区]    3k-4k
3            3   高级数据分析师（python MySQL)  西安    [沣惠南路]  10k-16k
4            4                   数据分析师  西安   [旺座现代城]    3k-6k
5            5                  数据分析专员  西安     [雁塔区]    5k-6k
6            6                   数据分析师  西安     [新城区]    4k-6k
7            7                   数据分析员  西安  [高新技术产…]    3k-6k
8            8  安全数据分析工程师(ESM)(J11929)  西安     [雁塔区]  11k-18k
9            9               数据分析开发工程师  西安  [高新技术产…]   8k-10k
10          10                   数据分析师  西安     [莲湖区]   6k-11k
11          11                 数据分析实习生  西安  [高新技术产…]    2k-3k

                   工位要求          公司名称                         公司级别  \
0     4k-7k 经验1-3年 / 本科          字节跳动         文娱丨内容 / C轮 / 2000人以上
1     4k-8k 经验1-3年 / 大专         美国亚米网       电商,消费生活 / A轮 / 50-150人
2       3k-4k 经验不限 / 大专          维视科技         移动互联网 / A轮 / 50-150人
3   10k-16k 经验3-5年 / 本科           贝业思  数据服务,移动互联网 / 不需要融资 / 15-50人
4     3k-6k 经验1-3年 / 本科       Atomobi      移动互联网,游戏 / 天使轮 / 15-50人
5     5k-6k 经验1-3年 / 本科          西安鼎胜        移动互联网 / 未融资 / 2000人以上
6     4k-6k 经验1-3年 / 本科  西安天邦测绘科技有限公司         移动互联网 / 未融资 / 15-50人
7     3k-6k 经验1-3年 / 大专          爱特眼动     移动互联网,数据服务 / 未融资 / 少于15人
8   11k-18k 经验1-3年 / 本科          绿盟科技      信息安全 / 上市公司 / 500-2000人
9    8k-10k 经验3-5年 / 本科          讯格软件     数据服务,企业服务 / 未融资 / 15-50人
10   6k-11k 经验3-5年 / 本科          字节跳动         文娱丨内容 / C轮 / 2000人以上
11      2k-3k 经验不限 / 大专          爱特眼动     移动互联网,数据服务 / 未融资 / 少于15人

                               岗位技能                                       公司短评
0           扁平管理 弹性工作 大厨定制三餐 就近租房补贴  “六险一金，弹性工作，餐补，租房补贴，带薪休假，休闲下午茶，扁平管理，团队氛围好”
1                 交通补助 弹性工作 帅哥多 领导好                       “十三薪；五险一金；出国机会；弹性工作”
2               大数据 移动互联网 数据挖掘 数据分析                      “精英团队,美资企业,深度学习,人工智能”
3                               大数据                      “股权激励,五险一金,算法牛人,扁平管理”
4                              数据分析                     “五险一金，下午茶，节假日礼品，不定时旅游”
5                         SPSS 数据分析                      “缴纳社保 员工福利 生日礼物 团建活动”
6                     数据分析 SPSS SQL                            “五险一金、补助、奖金、体检”
7                              数据分析                        “扁平化管理、发展空间大、团队氛围好”
8   信息安全 大数据 Hadoop Spark 数据分析 数据挖掘                     “上市公司；弹性工作；待遇优厚；优秀导师；”
9                    大数据 移动互联网 数据分析                           “定期体检 周末双休 节日福利”
10                               内容                        “六险一金，弹性工作，餐补，租房补贴”
11                             数据分析                        “扁平化管理、发展空间大、团队氛围好”  , 'changsha':     Unnamed: 0             标题  城市    公司地点     薪资待遇                  工位要求  \
0            0  数据分析师（SB0902）  长沙   [岳麓区]   8k-10k    8k-10k 经验1-3年 / 本科
1            1          数据分析师  长沙   [天心区]   8k-15k    8k-15k 经验1-3年 / 不限
2            2          数据分析师  长沙   [天心区]   8k-12k    8k-12k 经验1-3年 / 本科
3            3        数据分析工程师  长沙    [麓谷]  13k-15k  13k-15k 经验5-10年 / 本科
4            4        数据分析/运营  长沙   [咸嘉湖]  10k-18k  10k-18k 经验5-10年 / 本科
5            5        数据分析工程师  长沙   [张公岭]   8k-15k    8k-15k 经验3-5年 / 本科
6            6        数据分析工程师  长沙   [天心区]  10k-15k  10k-15k 经验5-10年 / 本科
7            7         大数据分析师  长沙   [长沙县]  30k-60k  30k-60k 经验5-10年 / 本科
8            8         大数据分析师  长沙   [袁家岭]   8k-10k    8k-10k 经验3-5年 / 本科
9            9         数据分析专员  长沙   [五里牌]    4k-8k     4k-8k 经验1-3年 / 本科
10          10           数据分析  长沙   [荷花园]    6k-8k     6k-8k 经验3-5年 / 本科
11          11       研究院数据分析师  长沙   [天心区]   6k-10k      6k-10k 经验不限 / 硕士
12          12         数据分析专员  长沙   [五里牌]    4k-6k       4k-6k 经验不限 / 大专
13          13        数据分析管培生  长沙    [麓谷]    3k-5k    3k-5k 经验应届毕业生 / 本科
14          14     新媒体营销数据分析师  长沙  [广电中心]    6k-7k     6k-7k 经验1-3年 / 本科
15          15        数据分析实习生  长沙    [麓谷]    4k-6k    4k-6k 经验应届毕业生 / 本科

               公司名称                           公司级别  \
0              蜜獾信息       移动互联网 / 不需要融资 / 150-500人
1            E-jade    移动互联网,游戏 / 不需要融资 / 150-500人
2   湖南麓山云数据科技服务有限公司  移动互联网,数据服务 / 不需要融资 / 150-500人
3              中和农信     移动互联网,金融 / 不需要融资 / 2000人以上
4              58到家         消费生活 / D轮及以上 / 2000人以上
5     中通服创发科技有限责任公司     移动互联网,电商 / 上市公司 / 150-500人
6              致新医疗            其他 / 未融资 / 150-500人
7               中人网         企业服务 / 上市公司 / 150-500人
8              中兴华易         移动互联网 / 未融资 / 150-500人
9              山川咨询       企业服务,教育 / 未融资 / 150-500人
10         北京天意飞扬科技         电商,移动互联网 / 未融资 / 少于15人
11    长沙市云研网络科技有限公司      移动互联网,消费生活 / 未融资 / 15-50人
12             华澜环保          数据服务,硬件 / A轮 / 15-50人
13    步步高商业连锁股份有限公司         电商,金融 / 上市公司 / 2000人以上
14             芒果tv       文娱丨内容 / 上市公司 / 500-2000人
15             中和农信     移动互联网,金融 / 不需要融资 / 2000人以上

                            岗位技能                    公司短评
0                 数据分析 SQLServer  “五险一金,超长带薪期,周末双休,年终奖金”
1             游戏 移动互联网 数据分析 数据运营   “年轻化,扁平化管理,海外交流,弹性工作”
2   大数据 移动互联网 数据分析 数据运营 SQL SPSS             “学习机会,晋升空间”
3                       大数据 数据分析    “六险一金,带薪年假,广阔平台,工作餐”
4                本地生活 移动互联网 数据分析   “公司靠谱,产品靠谱,领导靠谱,团队靠谱”
5                           数据分析                 “一切皆可能”
6                   医疗健康 物流 数据分析     “五险一金 餐补 交通补助 通讯补助”
7     企业服务 大数据 算法 数据挖掘 数据架构 数据分析                  “产品研发”
8                大数据 Hadoop 数据分析    “五险一金，年终奖，定期体检，员工旅游”
9         大数据 企业服务 数据分析 SPSS 数据库     “五险 清晰的岗位定位 高底薪高提成”
10                 移动互联网 通信/网络设备          “五险一金 双休 运营总监”
11                     移动互联网 大数据       “双休、五险、半年调薪一次的机会”
12                      大数据 数据分析  “作贮备经理，工资高，五险一金，补贴，提成”
13                      数据分析 SQL  “五险一金周末双休年底双薪技能培训大牛团队”
14                       市场 数据分析           “一流的平台,丰厚的奖金”
15                     数据挖掘 数据分析   “七险一金,年底多薪，工会福利，带薪年假”  , 'wuhan':     Unnamed: 0                 标题   城市        地点     薪资待遇  \
0            0  高级数据分析（对标985/211）   武汉     [白沙洲]   8k-15k
1            1              数据分析师   武汉     [洪山区]  10k-20k
2            2              数据分析师   武汉  [东湖新技术…]  10k-15k
3            3              数据分析师   武汉     [洪山区]  20k-40k
4            4               数据分析   武汉  [东湖新技术…]   5k-10k
5            5             数据分析专员   武汉      [流芳]    6k-9k
6            6       数据分析师/数据产品经理   武汉      [流芳]  18k-36k
7            7            数据分析-武汉   武汉  [东湖新技术…]  15k-30k
8            8              数据分析师   武汉     [中北路]    4k-7k
9            9              数据分析师   武汉      [关山]   8k-12k
10          10            资深数据分析师   武汉     [硚口区]  15k-25k
11          11              数据分析师   武汉      [流芳]    5k-8k
12          12              数据分析师   武汉      [光谷]    5k-8k
13          13              数据分析师   武汉      [珞南]  10k-18k
14          14            数据分析师助理   武汉    [珞狮南路]    4k-5k
15          15             数据分析主管   武汉     [江夏区]  15k-20k
16          16         数据分析经理（光谷）   武汉  [东湖新技术…]  15k-30k
17          17            资深数据分析师   武汉  [东湖新技术…]  10k-20k
18          18             数据分析主管   武汉     [丁字桥]   8k-12k
19          19      数据分析师(J10441)   武汉      [关山]  15k-30k
20          20            高级数据分析师   武汉      [流芳]      NaN
21          21            高级数据分析师   武汉    [珞狮南路]  10k-20k
22          22            高级数据分析师   武汉      [东亭]  10k-15k
23          23        数据分析（校招/实习）  NaN  [东湖新技术…]      NaN
24          24          高级业务数据分析师  NaN      [光谷]  10k-15k
25          25            数据分析工程师  NaN  [东湖新技术…]  12k-18k
26          26            亚马逊数据分析   武汉     [白沙洲]   8k-13k
27          27              数据分析师   武汉     [洪山区]      NaN
28          28             数据分析经理   武汉     [中北路]  12k-20k
29          29            数据分析工程师   武汉      [关山]  10k-15k
30          30        商业化-高级数据分析师   武汉     [洪山区]   8k-16k
31          31           数据分析产品经理   武汉    [珞狮南路]   8k-15k
32          32              数据分析师   武汉  [东湖新技术…]   8k-10k
33          33   资深数据分析工程师\数据分析专家   武汉     [洪山区]  15k-30k
34          34              数据分析师   武汉     [江夏区]   7k-14k
35          35              数据分析师   武汉     [中北路]   8k-15k
36          36          安全数据分析工程师   武汉  [东湖新技术…]  10k-14k
37          37            数据分析工程师   武汉     [武昌区]   9k-15k
38          38       数据分析专员（英语六级）   武汉  [东湖新技术…]    4k-6k
39          39          数据分析主管/经理   武汉      [关山]  20k-30k
40          40          数据分析算法工程师   武汉       NaN  10k-20k
41          41            风控数据分析师   武汉      [流芳]  10k-18k
42          42        商业化-高级数据分析师   武汉     [洪山区]   6k-12k
43          43         商业化-数据分析支持   武汉     [洪山区]   5k-10k
44          44         高级数据分析产品经理   武汉      [鲁巷]  25k-40k

                    岗位要求                名称                             级别  \
0     8k-15k 经验1-3年 / 本科            易佰网络科技        电商,移动互联网 / B轮 / 2000人以上
1      10k-20k 经验不限 / 不限              悦然心动        社交,游戏 / 上市公司 / 150-500人
2   10k-15k 经验5-10年 / 本科              盛天网络    游戏,文娱丨内容 / 上市公司 / 500-2000人
3    20k-40k 经验3-5年 / 本科              字节跳动           文娱丨内容 / C轮 / 2000人以上
4       5k-10k 经验不限 / 大专              诸葛io       企业服务,数据服务 / A轮 / 50-150人
5      6k-9k 经验3-5年 / 本科              天贝科技         移动互联网 / 未融资 / 150-500人
6   18k-36k 经验5-10年 / 本科                小米           硬件 / D轮及以上 / 2000人以上
7   15k-30k 经验5-10年 / 本科       深圳市丰巢科技有限公司          消费生活 / A轮 / 500-2000人
8      4k-7k 经验1-3年 / 本科          长江云新媒体集团    移动互联网,数据服务 / 未融资 / 150-500人
9     8k-12k 经验3-5年 / 本科              斗鱼直播        文娱丨内容 / D轮及以上 / 2000人以上
10   15k-25k 经验3-5年 / 本科       Today今天连锁便利          消费生活 / B轮 / 500-2000人
11     5k-8k 经验1-3年 / 大专              去哪儿网           旅游 / 不需要融资 / 2000人以上
12     5k-8k 经验1-3年 / 大专               小红书       消费生活 / D轮及以上 / 500-2000人
13   10k-18k 经验1-3年 / 本科               跟谁学      移动互联网,教育 / 上市公司 / 2000人以上
14       4k-5k 经验不限 / 大专        福韵数据服务有限公司     移动互联网,数据服务 / A轮 / 150-500人
15  15k-20k 经验5-10年 / 本科              盛天网络    游戏,文娱丨内容 / 上市公司 / 500-2000人
16   15k-30k 经验3-5年 / 本科              字节跳动           文娱丨内容 / C轮 / 2000人以上
17  10k-20k 经验5-10年 / 本科             途虎养车网        汽车丨出行 / D轮及以上 / 2000人以上
18    8k-12k 经验3-5年 / 大专  时时同云科技（成都）有限责任公司      移动互联网,消费生活 / C轮 / 2000人以上
19     15k-30k 经验不限 / 硕士               百分点       数据服务 / D轮及以上 / 500-2000人
20  12k-20k 经验5-10年 / 本科        优品财富管理有限公司           金融 / 未融资 / 500-2000人
21   10k-20k 经验3-5年 / 不限        福韵数据服务有限公司     移动互联网,数据服务 / A轮 / 150-500人
22   10k-15k 经验3-5年 / 本科             中国婚博会         其他 / 不需要融资 / 500-2000人
23    4k-8k 经验应届毕业生 / 本科                微派              社交 / B轮 / 50-150人
24   10k-15k 经验3-5年 / 本科               小红书       消费生活 / D轮及以上 / 500-2000人
25  12k-18k 经验应届毕业生 / 本科                极验       信息安全,数据服务 / B轮 / 50-150人
26      8k-13k 经验不限 / 本科            易佰网络科技        电商,移动互联网 / B轮 / 2000人以上
27    5k-10k 经验1-3年 / 本科              掌游科技     移动互联网,游戏 / 上市公司 / 150-500人
28  12k-20k 经验5-10年 / 本科               安居客  移动互联网,消费生活 / 上市公司 / 500-2000人
29   10k-15k 经验3-5年 / 本科        海康威视武汉研发中心     信息安全,数据服务 / 上市公司 / 2000人以上
30           经验3-5年 / 本科              字节跳动           文娱丨内容 / C轮 / 2000人以上
31    8k-15k 经验1-3年 / 本科        福韵数据服务有限公司     移动互联网,数据服务 / A轮 / 150-500人
32   8k-10k 经验应届毕业生 / 硕士             看电影了没   移动互联网,文娱丨内容 / 不需要融资 / 15-50人
33  15k-30k 经验5-10年 / 本科              斗鱼直播        文娱丨内容 / D轮及以上 / 2000人以上
34         7k-14k 经验3-5年   烽火科技·虹旭信息技术有限公司   信息安全,数据服务 / 不需要融资 / 150-500人
35   8k-15k 经验5-10年 / 本科               安居客  移动互联网,消费生活 / 上市公司 / 500-2000人
36   10k-14k 经验1-3年 / 本科              绿盟科技        信息安全 / 上市公司 / 500-2000人
37      9k-15k 经验不限 / 本科              天风证券           金融 / 不需要融资 / 2000人以上
38       4k-6k 经验不限 / 本科              普利菲特              电商 / 未融资 / 15-50人
39  20k-30k 经验5-10年 / 本科              慧控科技        移动互联网 / 不需要融资 / 50-150人
40   10k-20k 经验3-5年 / 硕士              三藏科技            软件开发 / 未融资 / 15-50人
41   10k-18k 经验3-5年 / 本科              天贝科技         移动互联网 / 未融资 / 150-500人
42    6k-12k 经验3-5年 / 本科              字节跳动           文娱丨内容 / C轮 / 2000人以上
43    5k-10k 经验1-3年 / 本科              字节跳动           文娱丨内容 / C轮 / 2000人以上
44  25k-40k 经验5-10年 / 本科              斗鱼直播        文娱丨内容 / D轮及以上 / 2000人以上

                                 岗位技能                      短评
0                电商 算法 数据挖掘 数据分析 数据处理    “五险一金/节日福利/专业培训/全勤奖”
1                        可视化 数据库 数据分析           “带薪出国游；千万级用户”
2                           数据分析 数据运营               “福利好 发展快”
3                                数据分析  “弹性工作，免费三餐，晋升空间，团队氛围好”
4                        大数据 企业服务 SQL        “五险一金 带薪年假 定期团建”
5                       SPSS SQL 数据分析                 “双休 五险”
6                                 大数据    “五险一金、弹性工作、双休、团队氛围好”
7             物流 移动互联网 数据分析 数据处理 数据挖掘       “扁平化管理 大平台 薪酬福利好”
8                           数据分析 数据运营      “五险一金，饭补，交通费，周末双休”
9                                  分析    “下午茶；五险一金；弹性工作；前景好；”
10              新零售 电商 数据分析 数据挖掘 数据仓库           “平台大 发展快 不打卡”
11                            电商 数据分析        “弹性时间 周末双休 五险一金”
12                         移动互联网 数据分析   “六险一金 周末双休 13薪 定期体检等”
13              移动互联网 教育 数据分析 SQL 数据库   “周末双休、六险一金、带薪年假、员工旅游”
14         信息安全 大数据 数据分析 SQL SPSS 数据库   “助理-初一级-初二级-中一级等上升平台”
15                电商 可视化 BI 数据分析 数据运营               “福利好 发展快”
16                               数据分析     “六险一金，餐补，租房补贴，带薪休假”
17                    大数据 BI 可视化 数据分析       “一年多次调,优秀团队,地铁周边”
18                     本地生活 数据分析 数据处理             “六险一金 阿里背景”
19                               数据分析             “技术大牛，福利齐全”
20               移动互联网 SQLServer 数据仓库     “BAT团队,团队氛围好,晋升空间大”
21          数据分析 数据挖掘 SQLServer MySQL           “五险一金，年终奖，培训”
22                     数据仓库 数据分析 数据挖掘          “五险一金 弹性工作 双休”
23                               数据分析             “发展空间大,大牛带”
24                               数据分析   “六险一金 周末双休 13薪 定期体检等”
25                      大数据 数据挖掘 数据分析        “有挑战性,技术先驱,大牛队友”
26                            电商 数据分析     “五险一金下午茶全勤带薪年假法定假等”
27                          数据分析 数据运营   “流水过亿,扁平管理,专业团队,定期培训”

In [7]:
lagou_dict['zhengzhou']

,Unnamed: 0,标题,城市,公司地点,薪资待遇,工位要求,公司名称,公司级别,岗位技能,公司短评
0,0,数据分析,郑州,[北林路],6k-8k,6k-8k 经验1-3年 / 大专,卓影科技,其他 / 上市公司 / 150-500人,数据运营,“五险一金、带薪年假、节日福利、加班补助”
1,1,数据分析（互联网运营中心）,郑州,[高新区],12k-24k,12k-24k 经验3-5年 / 本科,中移在线服务有限公司,移动互联网 / 不需要融资 / 2000人以上,教育 数据挖掘 数据分析,"“领导好,扁平化,福利多,空间大”"
2,2,商业化-数据分析经理,郑州,[金水区],15k-25k,15k-25k 经验3-5年 / 本科,字节跳动,文娱丨内容 / C轮 / 2000人以上,数据分析,“六险一金，餐补，租房补贴，带薪休假”
3,3,数据分析师,郑州,[北林路],4k-8k,4k-8k 经验1-3年 / 本科,戎易商智（北京）科技有限公司,"移动互联网,数据服务 / 未融资 / 15-50人",通信/网络设备 移动互联网 SPSS 数据分析,“周末双休，五险一金，带薪年假”
4,4,大数据分析师,郑州,[管城回族区],30k-40k,30k-40k 经验5-10年 / 不限,宇通客车,企业服务 / 上市公司 / 2000人以上,BI SPSS 数据分析,“高薪、福利待遇、假期多”
5,5,金融数据分析师,郑州,[金水区],6k-10k,6k-10k 经验不限 / 大专,河南千山教育科技有限公司,金融 / 未融资 / 50-150人,证券 股票 证券分析,“薪资待遇：8K~10K 双休”
6,6,大数据分析开发工程师助理/实习生,郑州,[经开区],4k-6k,4k-6k 经验不限 / 大专,缓冲网络科技,"移动互联网,人工智能 / 上市公司 / 500-2000人",工具软件 移动互联网 数据挖掘 数据架构 数据仓库 算法,“包住，发展前景大”
7,7,大数据分析师,郑州,[高新区],15k-25k,15k-25k 经验3-5年 / 本科,中移在线服务有限公司,移动互联网 / 不需要融资 / 2000人以上,数据分析 SQL,“海量数据 优质平台 发展空间大”
8,8,政企大数据分析师,郑州,[高新区],10k-20k,10k-20k 经验应届毕业生 / 本科,中移在线服务有限公司,移动互联网 / 不需要融资 / 2000人以上,分类信息 大数据 数据挖掘 数据架构 数据仓库 数据分析,“六险两金、扁平化管理”

## 批量删除表格里的第一列

In [8]:
for file in lagou_dict.values():
    file.drop(columns = 'Unnamed: 0', inplace = True)

In [9]:
lagou_dict['zhengzhou']

,标题,城市,公司地点,薪资待遇,工位要求,公司名称,公司级别,岗位技能,公司短评
0,数据分析,郑州,[北林路],6k-8k,6k-8k 经验1-3年 / 大专,卓影科技,其他 / 上市公司 / 150-500人,数据运营,“五险一金、带薪年假、节日福利、加班补助”
1,数据分析（互联网运营中心）,郑州,[高新区],12k-24k,12k-24k 经验3-5年 / 本科,中移在线服务有限公司,移动互联网 / 不需要融资 / 2000人以上,教育 数据挖掘 数据分析,"“领导好,扁平化,福利多,空间大”"
2,商业化-数据分析经理,郑州,[金水区],15k-25k,15k-25k 经验3-5年 / 本科,字节跳动,文娱丨内容 / C轮 / 2000人以上,数据分析,“六险一金，餐补，租房补贴，带薪休假”
3,数据分析师,郑州,[北林路],4k-8k,4k-8k 经验1-3年 / 本科,戎易商智（北京）科技有限公司,"移动互联网,数据服务 / 未融资 / 15-50人",通信/网络设备 移动互联网 SPSS 数据分析,“周末双休，五险一金，带薪年假”
4,大数据分析师,郑州,[管城回族区],30k-40k,30k-40k 经验5-10年 / 不限,宇通客车,企业服务 / 上市公司 / 2000人以上,BI SPSS 数据分析,“高薪、福利待遇、假期多”
5,金融数据分析师,郑州,[金水区],6k-10k,6k-10k 经验不限 / 大专,河南千山教育科技有限公司,金融 / 未融资 / 50-150人,证券 股票 证券分析,“薪资待遇：8K~10K 双休”
6,大数据分析开发工程师助理/实习生,郑州,[经开区],4k-6k,4k-6k 经验不限 / 大专,缓冲网络科技,"移动互联网,人工智能 / 上市公司 / 500-2000人",工具软件 移动互联网 数据挖掘 数据架构 数据仓库 算法,“包住，发展前景大”
7,大数据分析师,郑州,[高新区],15k-25k,15k-25k 经验3-5年 / 本科,中移在线服务有限公司,移动互联网 / 不需要融资 / 2000人以上,数据分析 SQL,“海量数据 优质平台 发展空间大”
8,政企大数据分析师,郑州,[高新区],10k-20k,10k-20k 经验应届毕业生 / 本科,中移在线服务有限公司,移动互联网 / 不需要融资 / 2000人以上,分类信息 大数据 数据挖掘 数据架构 数据仓库 数据分析,“六险两金、扁平化管理”

## 统计每一个城市分别有多少条数据

In [10]:
positions_num = pd.Series()
for key in lagou_dict:
    value = lagou_dict[key].shape[0]
    positions_num[key] = value
print(positions_num)

zhengzhou      9
xiamen        14
foshan        10
xian          12
changsha      16
wuhan         45
shenzhen     262
hangzhou     145
suzhou         8
guangzhou    177
chongqing      8
chengdu       46
shanghai     435
beijing      450
nanjing       30
tianjin        7
dtype: int64

/var/folders/0b/023xcpqx6_s3b3dv7nxprsf00000gn/T/ipykernel_83466/941728077.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  positions_num = pd.Series()

<!--  按照职位数排序 -->

In [11]:
# 按照职位多少排序
positions_num.sort_values(ascending = False)

beijing      450
shanghai     435
shenzhen     262
guangzhou    177
hangzhou     145
chengdu       46
wuhan         45
nanjing       30
changsha      16
xiamen        14
xian          12
foshan        10
zhengzhou      9
suzhou         8
chongqing      8
tianjin        7
dtype: int64

### 删除职位少于30条的数据

In [12]:
#新建一个字典，存放职位数据大于等于30的城市数据
lagou_dict_30 = {}

for key in lagou_dict:
    if lagou_dict[key].shape[0] >= 30:
        lagou_dict_30[key] = lagou_dict[key]
print(lagou_dict_30)

{'wuhan':                    标题   城市        地点     薪资待遇                  岗位要求  \
0   高级数据分析（对标985/211）   武汉     [白沙洲]   8k-15k    8k-15k 经验1-3年 / 本科
1               数据分析师   武汉     [洪山区]  10k-20k     10k-20k 经验不限 / 不限
2               数据分析师   武汉  [东湖新技术…]  10k-15k  10k-15k 经验5-10年 / 本科
3               数据分析师   武汉     [洪山区]  20k-40k   20k-40k 经验3-5年 / 本科
4                数据分析   武汉  [东湖新技术…]   5k-10k      5k-10k 经验不限 / 大专
5              数据分析专员   武汉      [流芳]    6k-9k     6k-9k 经验3-5年 / 本科
6        数据分析师/数据产品经理   武汉      [流芳]  18k-36k  18k-36k 经验5-10年 / 本科
7             数据分析-武汉   武汉  [东湖新技术…]  15k-30k  15k-30k 经验5-10年 / 本科
8               数据分析师   武汉     [中北路]    4k-7k     4k-7k 经验1-3年 / 本科
9               数据分析师   武汉      [关山]   8k-12k    8k-12k 经验3-5年 / 本科
10            资深数据分析师   武汉     [硚口区]  15k-25k   15k-25k 经验3-5年 / 本科
11              数据分析师   武汉      [流芳]    5k-8k     5k-8k 经验1-3年 / 大专
12              数据分析师   武汉      [光谷]    5k-8k     5k-8k 经验1-3年 / 大专
13              数据分析师   武汉      [珞南]  10k-18k   10k-18k 经验1-3年 / 本科
14            数据分析师助理   武汉    [珞狮南路]    4k-5k       4k-5k 经验不限 / 大专
15             数据分析主管   武汉     [江夏区]  15k-20k  15k-20k 经验5-10年 / 本科
16         数据分析经理（光谷）   武汉  [东湖新技术…]  15k-30k   15k-30k 经验3-5年 / 本科
17            资深数据分析师   武汉  [东湖新技术…]  10k-20k  10k-20k 经验5-10年 / 本科
18             数据分析主管   武汉     [丁字桥]   8k-12k    8k-12k 经验3-5年 / 大专
19      数据分析师(J10441)   武汉      [关山]  15k-30k     15k-30k 经验不限 / 硕士
20            高级数据分析师   武汉      [流芳]      NaN  12k-20k 经验5-10年 / 本科
21            高级数据分析师   武汉    [珞狮南路]  10k-20k   10k-20k 经验3-5年 / 不限
22            高级数据分析师   武汉      [东亭]  10k-15k   10k-15k 经验3-5年 / 本科
23        数据分析（校招/实习）  NaN  [东湖新技术…]      NaN    4k-8k 经验应届毕业生 / 本科
24          高级业务数据分析师  NaN      [光谷]  10k-15k   10k-15k 经验3-5年 / 本科
25            数据分析工程师  NaN  [东湖新技术…]  12k-18k  12k-18k 经验应届毕业生 / 本科
26            亚马逊数据分析   武汉     [白沙洲]   8k-13k      8k-13k 经验不限 / 本科
27              数据分析师   武汉     [洪山区]      NaN    5k-10k 经验1-3年 / 本科
28             数据分析经理   武汉     [中北路]  12k-20k  12k-20k 经验5-10年 / 本科
29            数据分析工程师   武汉      [关山]  10k-15k   10k-15k 经验3-5年 / 本科
30        商业化-高级数据分析师   武汉     [洪山区]   8k-16k           经验3-5年 / 本科
31           数据分析产品经理   武汉    [珞狮南路]   8k-15k    8k-15k 经验1-3年 / 本科
32              数据分析师   武汉  [东湖新技术…]   8k-10k   8k-10k 经验应届毕业生 / 硕士
33   资深数据分析工程师\数据分析专家   武汉     [洪山区]  15k-30k  15k-30k 经验5-10年 / 本科
34              数据分析师   武汉     [江夏区]   7k-14k         7k-14k 经验3-5年
35              数据分析师   武汉     [中北路]   8k-15k   8k-15k 经验5-10年 / 本科
36          安全数据分析工程师   武汉  [东湖新技术…]  10k-14k   10k-14k 经验1-3年 / 本科
37            数据分析工程师   武汉     [武昌区]   9k-15k      9k-15k 经验不限 / 本科
38       数据分析专员（英语六级）   武汉  [东湖新技术…]    4k-6k       4k-6k 经验不限 / 本科
39          数据分析主管/经理   武汉      [关山]  20k-30k  20k-30k 经验5-10年 / 本科
40          数据分析算法工程师   武汉       NaN  10k-20k   10k-20k 经验3-5年 / 硕士
41            风控数据分析师   武汉      [流芳]  10k-18k   10k-18k 经验3-5年 / 本科
42        商业化-高级数据分析师   武汉     [洪山区]   6k-12k    6k-12k 经验3-5年 / 本科
43         商业化-数据分析支持   武汉     [洪山区]   5k-10k    5k-10k 经验1-3年 / 本科
44         高级数据分析产品经理   武汉      [鲁巷]  25k-40k  25k-40k 经验5-10年 / 本科

                  名称                             级别  \
0             易佰网络科技        电商,移动互联网 / B轮 / 2000人以上
1               悦然心动        社交,游戏 / 上市公司 / 150-500人
2               盛天网络    游戏,文娱丨内容 / 上市公司 / 500-2000人
3               字节跳动           文娱丨内容 / C轮 / 2000人以上
4               诸葛io       企业服务,数据服务 / A轮 / 50-150人
5               天贝科技         移动互联网 / 未融资 / 150-500人
6                 小米           硬件 / D轮及以上 / 2000人以上
7        深圳市丰巢科技有限公司          消费生活 / A轮 / 500-2000人
8           长江云新媒体集团    移动互联网,数据服务 / 未融资 / 150-500人
9               斗鱼直播        文娱丨内容 / D轮及以上 / 2000人以上
10       Today今天连锁便利          消费生活 / B轮 / 500-2000人
11              去哪儿网           旅游 / 不需要融资 / 2000人以上
12               小红书       消费生活 / D轮及以上 / 500-2000人
13               跟谁学      移动互联网,教育 / 上市公司 / 2000人以上
14        福韵数据服务有限公司     移动互联网,数据服务 / A轮 / 150-500人
15              盛天网络    游戏,文娱丨内容 / 上市公司 / 500-2000人
16              字节跳动           文娱丨内容 / C轮 / 2000人以上
17             途虎养车网        汽车丨出行 / D轮及以上 / 2000人以上
18  时时同云科技（成都）有限责任公司      移动互联网,消费生活 / C轮 / 2000人以上
19               百分点       数据服务 / D轮及以上 / 500-2000人
20        优品财富管理有限公司           金融 / 未融资 / 500-2000人
21        福韵数据服务有限公司     移动互联网,数据服务 / A轮 / 150-500人
22             中国婚博会         其他 / 不需要融资 / 500-2000人
23                微派              社交 / B轮 / 50-150人
24               小红书       消费生活 / D轮及以上 / 500-2000人
25                极验       信息安全,数据服务 / B轮 / 50-150人
26            易佰网络科技        电商,移动互联网 / B轮 / 2000人以上
27              掌游科技     移动互联网,游戏 / 上市公司 / 150-500人
28               安居客  移动互联网,消费生活 / 上市公司 / 500-2000人
29        海康威视武汉研发中心     信息安全,数据服务 / 上市公司 / 2000人以上
30              字节跳动           文娱丨内容 / C轮 / 2000人以上
31        福韵数据服务有限公司     移动互联网,数据服务 / A轮 / 150-500人
32             看电影了没   移动互联网,文娱丨内容 / 不需要融资 / 15-50人
33              斗鱼直播        文娱丨内容 / D轮及以上 / 2000人以上
34   烽火科技·虹旭信息技术有限公司   信息安全,数据服务 / 不需要融资 / 150-500人
35               安居客  移动互联网,消费生活 / 上市公司 / 500-2000人
36              绿盟科技        信息安全 / 上市公司 / 500-2000人
37              天风证券           金融 / 不需要融资 / 2000人以上
38              普利菲特              电商 / 未融资 / 15-50人
39              慧控科技        移动互联网 / 不需要融资 / 50-150人
40              三藏科技            软件开发 / 未融资 / 15-50人
41              天贝科技         移动互联网 / 未融资 / 150-500人
42              字节跳动           文娱丨内容 / C轮 / 2000人以上
43              字节跳动           文娱丨内容 / C轮 / 2000人以上
44              斗鱼直播        文娱丨内容 / D轮及以上 / 2000人以上

                                 岗位技能                      短评
0                电商 算法 数据挖掘 数据分析 数据处理    “五险一金/节日福利/专业培训/全勤奖”
1                        可视化 数据库 数据分析           “带薪出国游；千万级用户”
2                           数据分析 数据运营               “福利好 发展快”
3                                数据分析  “弹性工作，免费三餐，晋升空间，团队氛围好”
4                        大数据 企业服务 SQL        “五险一金 带薪年假 定期团建”
5                       SPSS SQL 数据分析                 “双休 五险”
6                                 大数据    “五险一金、弹性工作、双休、团队氛围好”
7             物流 移动互联网 数据分析 数据处理 数据挖掘       “扁平化管理 大平台 薪酬福利好”
8                           数据分析 数据运营      “五险一金，饭补，交通费，周末双休”
9                                  分析    “下午茶；五险一金；弹性工作；前景好；”
10              新零售 电商 数据分析 数据挖掘 数据仓库           “平台大 发展快 不打卡”
11                            电商 数据分析        “弹性时间 周末双休 五险一金”
12                         移动互联网 数据分析   “六险一金 周末双休 13薪 定期体检等”
13              移动互联网 教育 数据分析 SQL 数据库   “周末双休、六险一金、带薪年假、员工旅游”
14         信息安全 大数据 数据分析 SQL SPSS 数据库   “助理-初一级-初二级-中一级等上升平台”
15                电商 可视化 BI 数据分析 数据运营               “福利好 发展快”
16                               数据分析     “六险一金，餐补，租房补贴，带薪休假”
17                    大数据 BI 可视化 数据分析       “一年多次调,优秀团队,地铁周边”
18                     本地生活 数据分析 数据处理             “六险一金 阿里背景”
19                               数据分析             “技术大牛，福利齐全”
20               移动互联网 SQLServer 数据仓库     “BAT团队,团队氛围好,晋升空间大”
21          数据分析 数据挖掘 SQLServer MySQL           “五险一金，年终奖，培训”
22                     数据仓库 数据分析 数据挖掘          “五险一金 弹性工作 双休”
23                               数据分析             “发展空间大,大牛带”
24                               数据分析   “六险一金 周末双休 13薪 定期体检等”
25                      大数据 数据挖掘 数据分析        “有挑战性,技术先驱,大牛队友”
26                            电商 数据分析     “五险一金下午茶全勤带薪年假法定假等”
27                          数据分析 数据运营   “流水过亿,扁平管理,专业团队,定期培训”
28                          策略运营 数据分析        “五险一金、年终奖、超长过年假”
29                                大数据              “六险一金；大平台”
30                               项目管理     “六险一金，餐补，带薪休假，扁平管理”
31            大数据 产品设计 需求分析 数据分析 项目管理           “五险一金，年终奖，培训”
32                   视频 SPSS 数据分析 SQL      “粉丝多 ；福利多；前景好；不官僚”
33                      大数据 数据挖掘 数据分析           “行业发展快,公司发展好”
34                          数据分析 数据运营  “班车,提供食宿,奖金,薪酬增长,沟通畅通”
35                          数据运营 数据分析        “五险一金、年终奖、超长过年假”
36                          信息安全 数据分析        “五险一金；绩效奖金；股票期权”
37  证券/期货 MySQL Oracle Java SQLServer      “精英团队,发展空间大,福利待遇好”
38                 大数据 广告营销 数据分析 数据运营             “弹性工作，五险一金”
39                               数据分析           “五险一金 三个月年终奖”
40                         建模 机器学习 算法  “办公环境优、资深大佬指导、领导超Nice”
41              大数据 移动互联网 可视化 数据分析 商业     “发展空间大高薪高福利出国游周末双休”
42             移动互联网 数据分析 行业分析 市场竞争分析   “六险一金、团队氛围好、餐补、扁平化管理”
43                          广告营销 技术支持  “六险一金、团队氛围好、带薪休假、晋升空间”
44                            直播 数据分析            “发展空间大，福利齐全”  , 'shenzhen':                       标题  城市   公司地点     薪资待遇                  工位要求  \
0                  数据分析师  深圳  [科技园]  10k-20k   10k-20k 经验3-5年 / 本科
1           032281-数据分析岗  深圳  [福田区]  11k-20k   11k-20k 经验1-3年 / 本科
2                  数据分析师  深圳  [宝安区]   8k-15k    8k-15k 经验1-3年 / 本科
3                  数据分析师  深圳   [前海]  10k-20k   10k-20k 经验3-5年 / 不限
4    数据分析师（2020珍爱秋季校园招聘）  深圳  [南山区]  15k-25k  15k-25k 经验应届毕业生 / 本科
..                   ...  ..    ...      ...                   ...
257              风控数据分析师  深圳  [南山区]  13k-20k   13k-20k 经验3-5年 / 本科
258        广告数据分析师leader  深圳   [新安]  35k-60k  35k-60k 经验5-10年 / 博士
259        广告数据分析师leader  深圳   [新安]  25k-50k  25k-50k 经验5-10年 / 本科
260    增长经理/增长黑客（数据分析方向）  深圳  [南山区]  30k-50k  30k-50k 经验5-10年 / 本科
261       SL产品运营经理（数据分析）  深圳   [后海]  15k-30k  15k-30k 经验5-10年 / 本科

             公司名称                       公司级别                 岗位技能  \
0            木槿科技    数据服务 / 不需要融资 / 150-500人   大数据 互联网金融 数据分析 SQL
1            平安产险        金融 / 上市公司 / 2000人以上                 人力资源
2      新锐居品科技有限公司     电商,消费生活 / A轮 / 50-150人  电商 数据分析 数据运营 可视化 BI
3             迷你玩         游戏 / B轮 / 150-500人         教育 数据分析 数据运营
4             珍爱网  社交,消费生活 / 不需要融资 / 2000人以上                 数据分析
..            ...                        ...                  ...
257  深圳白骑士大数据有限公司     企业服务,金融 / A轮 / 50-150人      数据库 数据分析 SQL BI
258          京东集团        电商 / 上市公司 / 2000人以上          电商 大数据 数据分析
259          京东集团        电商 / 上市公司 / 2000人以上    电商 数据分析 SQLServer
260            极光    企业服务 / 上市公司 / 500-2000人             大数据 数据分析
261      顺丰科技有限公司    物流丨运输 / 不需要融资 / 2000人以上                   其他

                       公司短评
0    “AI金融科技、发展前景大、股东方实力雄厚”
1     “五险一金,绩效奖金,带薪年假,定期体检”
2             “跨国团队，订单起量时刻”
3       “领导好，年终奖，下午茶，扁平化管理”
4          “工作环境佳,平台大,周末双休”
..                      ...
257          “高速发展,创新型,有挑战”
258  “500强，免费班车，五险一金，带薪年休假”
259  “500强，免费班车，五险一金，带薪年休假”
260      “大数据平台,纳斯达克,扁平化管理”
261                 “发展空间大”

[262 rows x 9 columns], 'hangzhou':                          标题  城市   公司地点     薪资待遇                  工位要求  \
0                      数据分析  杭州  [西湖区]  10k-15k   10k-15k 经验1-3年 / 本科
1                      数据分析  杭州  [西湖区]  10k-16k   10k-16k 经验1-3年 / 本科
2                   资深数据分析师  杭州  [西湖区]  18k-32k   18k-32k 经验3-5年 / 本科
3              数据分析师（消费品行业）  杭州   [仓前]   6k-10k    6k-10k 经验1-3年 / 不限
4                  数据分析高级专家  杭州  [拱墅区]  20k-30k   20k-30k 经验3-5年 / 本科
..                      ...  ..    ...      ...                   ...
140                大数据分析工程师  杭州  [西湖区]  15k-22k  15k-22k 经验5-10年 / 不限
141  初级金融、互联网 数据分析挖掘机器学习研究岗  杭州   [江南]  10k-20k   10k-20k 经验1-3年 / 硕士
142             大数据分析与模型建设岗  杭州   [望江]  25k-30k   25k-30k 经验1-3年 / 本科
143               大数据分析项目经理  杭州   [西兴]  15k-20k   15k-20k 经验3-5年 / 本科
144                商业数据分析总监  杭州   [长河]  60k-80k  60k-80k 经验10年以上 / 本科

             公司名称                           公司级别  \
0             婚礼纪       消费生活 / D轮及以上 / 500-2000人
1              微店            电商 / C轮 / 500-2000人
2              有赞            电商 / 上市公司 / 2000人以上
3     polosport服饰   数据服务,移动互联网 / 不需要融资 / 50-150人
4    大箴（杭州）科技有限公司        电商,金融 / 不需要融资 / 50-150人
..            ...                            ...
140            微选      移动互联网,电商 / 未融资 / 150-500人
141          长亮科技          企业服务 / 上市公司 / 2000人以上
142          泰隆银行           金融 / 不需要融资 / 2000人以上
143          安恒信息  信息安全,数据服务 / D轮及以上 / 500-2000人
144            网易            电商 / 上市公司 / 2000人以上

                                岗位技能                  公司短评
0                              MySQL      “六险一金、年终奖、发展空间大”
1                             电商 SQL      “独立负责 奖金期权多 福利好”
2                 电商 Hive 数据分析 MySQL         “发展空间大、福利待遇好”
3               电商 数据分析 数据运营 SPSS 商业  “五险一金 带薪年假 餐补 扁平化组织”
4                            大数据 云计算      “高薪 高成长 轻松的工作氛围”
..                               ...                   ...
140                           电商 新零售               “发展空间大”
141                     算法 数据挖掘 数据分析  “金融科技,学习环境,提升空间,大平台”
142                         大数据 数据分析          “薪酬丰厚、亲情a+b”
143                             信息安全     “五险一金 带薪年假 国内外旅游”
144  电商 移动互联网 SQLServer Hive 数据分析 算法         “跨境电商，薪酬有竞争力”

[145 rows x 9 columns], 'guangzhou':                  标题  城市    公司地点     薪资待遇                  工位要求          公司名称  \
0              数据分析  广州   [天河区]    4k-8k     4k-8k 经验1-3年 / 本科          细刻科技
1             数据分析师  广州    [五山]  20k-40k   20k-40k 经验1-3年 / 本科        wlaike
2             数据分析师  广州  [珠江新城]  10k-20k     10k-20k 经验不限 / 本科            趣丸
3            数据分析专家  广州    [大石]  25k-50k  25k-50k 经验5-10年 / 本科  欢聚时代（YY Inc）
4              数据分析  广州   [天河区]  12k-24k   12k-24k 经验3-5年 / 本科            网易
..              ...  ..     ...      ...                   ...           ...
172  数据挖掘工程师（数据分析师）  广州   [天河区]   8k-15k    8k-15k 经验3-5年 / 不限            BW
173    市场研究员（数据分析师）  广州   [番禺区]    5k-9k     5k-9k 经验1-3年 / 本科          汉兴科技
174       工业大数据分析专家  广州   [番禺区]  30k-40k  30k-40k 经验5-10年 / 本科        美的集团IT
175      IOT大数据分析专家  广州   [番禺区]  30k-40k  30k-40k 经验5-10年 / 本科        美的集团IT
176        大数据分析工程师  广州   [天河区]  13k-22k   13k-22k 经验3-5年 / 本科           租租车

                           公司级别                        岗位技能  \
0     移动互联网,电商 / A轮 / 500-2000人                 电商 数据运营 数据库
1    移动互联网,企业服务 / B轮 / 150-500人                    数据分析 SQL
2         游戏 / 不需要融资 / 150-500人                        数据分析
3        文娱丨内容 / 上市公司 / 2000人以上                  直播 视频 数据分析
4           电商 / 上市公司 / 2000人以上                 SQL 数据运营 BI
..                          ...                         ...
172    企业服务,数据服务 / 未融资 / 15-50人  企业服务 大数据 数据挖掘 数据分析 算法 数据处理
173    移动互联网,企业服务 / 天使轮 / 少于15人     电商 新零售 数据分析 市场分析 市场竞争分析
174         硬件 / 上市公司 / 2000人以上   大数据 移动互联网 人工智能 建模 算法 数据挖掘
175         硬件 / 上市公司 / 2000人以上           大数据 移动互联网 BI 数据分析
176    旅游,消费生活 / C轮 / 500-2000人                  ETL Hadoop

                       公司短评
0     “双休，五险一金，餐补，生日会，加班补贴”
1    “牛人多 交通补贴 餐补 绩效奖 海外旅游”
2        “五险一金,包三餐,大牛多,空间大”
3            “上市公司 互联网 大平台”
4       “6险1金 16薪 免费食堂 健身房”
..                      ...
172     “气氛好,有潜力,学习机会多,人性化”
173      “优秀团队,氛围好,绩效奖金，住宿”
174    “六险一金,餐补,节日福利,免费健身房”
175    “六险一金,餐补,节日福利,免费健身房”
176   “周末双休,海外旅游,带薪年假,年终奖金”

[177 rows x 9 columns], 'chengdu':                            标题  城市   公司地点     薪资待遇                  工位要求  \
0             数据分析 (MJ000445)  成都   [玉林]   6k-12k    6k-12k 经验1-3年 / 不限
1               数据分析实习生（运营方向）  成都  [成华区]    2k-3k    2k-3k 经验应届毕业生 / 本科
2                     高级数据分析师  成都  [高新区]  10k-20k  10k-20k 经验5-10年 / 本科
3                      大数据分析师  成都   [华阳]  15k-25k   15k-25k 经验1-3年 / 本科
4                       数据分析师  成都  [高新区]  12k-18k  12k-18k 经验5-10年 / 本科
5                       数据分析师  成都   [中和]  10k-20k     10k-20k 经验不限 / 本科
6                       数据分析师  成都  [高新区]  15k-30k  15k-30k 经验5-10年 / 本科
7                       数据分析师  成都   [郫县]   6k-10k    6k-10k 经验1-3年 / 大专
8                       数据分析师  成都  [高新区]   8k-16k    8k-16k 经验1-3年 / 本科
9                        数据分析  成都  [武侯区]  12k-20k     12k-20k 经验不限 / 硕士
10                      数据分析师  成都   [石羊]   8k-10k    8k-10k 经验1-3年 / 本科
11                    数据分析工程师  成都  [高新区]    5k-9k     5k-9k 经验3-5年 / 本科
12                游戏运营-数据分析方向  成都  [高新区]  10k-20k   10k-20k 经验3-5年 / 本科
13                      数据分析师  成都  [高新区]   8k-10k    8k-10k 经验1-3年 / 本科
14                 数据分析师-挖掘方向  成都  [高新区]   8k-15k    8k-15k 经验1-3年 / 本科
15                      数据分析师  成都   [玉林]   6k-12k    6k-12k 经验1-3年 / 大专
16                      数据分析师  成都  [跳伞塔]  14k-20k  14k-20k 经验5-10年 / 本科
17                      数据分析师  成都  [九里堤]  11k-18k   11k-18k 经验3-5年 / 本科
18                    数据分析工程师  成都  [高新区]  15k-25k     15k-25k 经验不限 / 本科
19                     数据分析经理  成都  [武侯区]   7k-10k   7k-10k 经验5-10年 / 本科
20        高级计量模型及数据分析经理G00083  成都  [高新区]  20k-35k  20k-35k 经验5-10年 / 硕士
21              初级数据分析师（分析方向）  成都  [高新区]    4k-7k     4k-7k 经验1年以下 / 不限
22           数据分析专家/Leader/总监  成都   [石羊]  20k-40k  20k-40k 经验5-10年 / 硕士
23                   中高级数据分析师  成都  [高新区]  10k-20k   10k-20k 经验3-5年 / 本科
24                     大数据分析师  成都  [高新区]  14k-20k   14k-20k 经验3-5年 / 本科
25                      数据分析师  成都  [猛追湾]    3k-5k     3k-5k 经验1年以下 / 大专
26                   数据分析（英语）  成都   [中和]    6k-8k     6k-8k 经验1-3年 / 不限
27                    资深数据分析师  成都  [盐市口]   7k-12k    7k-12k 经验3-5年 / 大专
28                     数据分析专员  成都  [高新区]    3k-5k       3k-5k 经验不限 / 大专
29                  数据分析师（业务）  成都  [高新区]    5k-8k       5k-8k 经验不限 / 本科
30                     数据分析专员  成都   [玉林]   8k-12k    8k-12k 经验3-5年 / 本科
31                     数据分析助理  成都  [高新区]   5k-10k      5k-10k 经验不限 / 不限
32                       数据分析  成都  [跳伞塔]   6k-10k    6k-10k 经验3-5年 / 本科
33             数据分析岗（2019年校招）  成都   [桂溪]    6k-8k    6k-8k 经验应届毕业生 / 本科
34                      数据分析师  成都   [石羊]   6k-10k    6k-10k 经验1-3年 / 本科
35         数据分析师-Data Analyst  成都  [高新区]  10k-15k   10k-15k 经验1-3年 / 本科
36                     数据分析专员  成都   [金沙]    4k-6k       4k-6k 经验不限 / 不限
37             数据分析专员/数据分析实习生  成都  [高新区]    3k-5k       3k-5k 经验不限 / 大专
38                数据分析工程师（成都）  成都  [高新区]  12k-16k  12k-16k 经验5-10年 / 本科
39                 数据分析助理（实习）  成都  [高新区]    2k-4k       2k-4k 经验不限 / 不限
40  生物信息工程师/基因数据分析师 （流程维护/数据质  成都  [高新区]  15k-30k   15k-30k 经验3-5年 / 硕士
41                    医疗数据分析师  成都  [武侯区]    4k-8k     4k-8k 经验1-3年 / 本科
42                  大数据分析（驻场）  成都  [双流区]  15k-30k  15k-30k 经验5-10年 / 本科
43             游戏运营策划(数据分析方向)  成都  [高新区]   8k-15k      8k-15k 经验不限 / 本科
44             游戏运营专员（数据分析方向）  成都  [高新区]   6k-12k    6k-12k 经验1-3年 / 本科
45                物流数据分析岗（成都）  成都  [新都区]   5k-10k    5k-10k 经验1-3年 / 本科

              公司名称                            公司级别  \
0              有利网            金融 / 不需要融资 / 2000人以上
1             字节跳动            文娱丨内容 / C轮 / 2000人以上
2             我行我数     移动互联网,数据服务 / 不需要融资 / 15-50人
3    成都聚思力信息技术有限公司     移动互联网,电商 / 上市公司 / 500-2000人
4             极米科技       电商,硬件 / D轮及以上 / 500-2000人
5             西瓜创客              教育 / A轮 / 150-500人
6             新网银行           金融 / 不需要融资 / 150-500人
7           Huatek       电商,移动互联网 / 未融资 / 150-500人
8             乐信圣文        游戏,医疗丨健康 / B轮 / 150-500人
9         XGATE讯格得    移动互联网,企业服务 / 不需要融资 / 50-150人
10            易我科技     移动互联网,游戏 / 不需要融资 / 150-500人
11            优彼致愿        移动互联网,教育 / B轮 / 150-500人
12           91Act            游戏 / 不需要融资 / 50-150人
13      DataCastle            移动互联网 / 天使轮 / 15-50人
14            映潮科技            数据服务 / 未融资 / 50-150人
15             有利网            金融 / 不需要融资 / 2000人以上
16            万益能源     企业服务,数据服务 / 不需要融资 / 50-150人
17  成都交投智慧停车科技有限公司    移动互联网,人工智能 / 不需要融资 / 50-150人
18            西瓜创客              教育 / A轮 / 150-500人
19             中非网         电商,企业服务 / A轮 / 150-500人
20            希望金科     移动互联网,金融 / 不需要融资 / 150-500人
21            映潮科技            数据服务 / 未融资 / 50-150人
22            易我科技     移动互联网,游戏 / 不需要融资 / 150-500人
23           联通大数据         数据服务 / 不需要融资 / 150-500人
24            积微物联  移动互联网,消费生活 / 不需要融资 / 500-2000人
25             房助拍              其他 / 未融资 / 50-150人
26             VXI       移动互联网 / 不需要融资 / 500-2000人
27            御顺投资    移动互联网,金融 / 不需要融资 / 500-2000人
28            蚂蚁物流            其他 / 不需要融资 / 2000人以上
29            知道创宇           信息安全 / C轮 / 500-2000人
30             有利网            金融 / 不需要融资 / 2000人以上
31            西瓜创客              教育 / A轮 / 150-500人
32            京东物流          物流丨运输 / 上市公司 / 2000人以上
33        锦程消费金融公司             金融 / 未融资 / 150-500人
34            亿嘉联创     企业服务,移动互联网 / 不需要融资 / 15-50人
35            申帝科技          数据服务,金融 / 未融资 / 15-50人
36            环球车享              其他 / 未融资 / 50-150人
37            蚂蚁物流            其他 / 不需要融资 / 2000人以上

In [13]:
lagou_dict_30.keys()

dict_keys(['wuhan', 'shenzhen', 'hangzhou', 'guangzhou', 'chengdu', 'shanghai', 'beijing', 'nanjing'])

### 批量统计这些表格的数据

In [14]:
for key in lagou_dict_30:
    print(key)
    print(lagou_dict_30[key].isnull().sum())

wuhan
标题      0
城市      3
地点      1
薪资待遇    3
岗位要求    0
名称      0
级别      0
岗位技能    0
短评      0
dtype: int64
shenzhen
标题      0
城市      0
公司地点    0
薪资待遇    0
工位要求    0
公司名称    0
公司级别    0
岗位技能    0
公司短评    0
dtype: int64
hangzhou
标题      0
城市      0
公司地点    0
薪资待遇    0
工位要求    0
公司名称    0
公司级别    0
岗位技能    0
公司短评    0
dtype: int64
guangzhou
标题      0
城市      0
公司地点    0
薪资待遇    0
工位要求    0
公司名称    0
公司级别    0
岗位技能    0
公司短评    0
dtype: int64
chengdu
标题      0
城市      0
公司地点    0
薪资待遇    0
工位要求    0
公司名称    0
公司级别    0
岗位技能    1
公司短评    0
dtype: int64
shanghai
标题      0
城市      0
公司地点    0
薪资待遇    0
工位要求    0
公司名称    0
公司级别    0
岗位技能    1
公司短评    0
dtype: int64
beijing
标题      0
公司地点    0
薪资待遇    0
工位要求    0
公司名称    0
公司级别    0
岗位技能    1
公司短评    0
dtype: int64
nanjing
标题      0
城市      2
公司地点    1
薪资待遇    2
工位要求    0
公司名称    1
公司级别    0
岗位技能    0
公司短评    0
dtype: int64

### 对城市列进行填充（按照众数填充）: beijing 没有城市这一列，如果没有这一列的话，添加城市列兵填充

In [15]:
# lagou_dict_30[城市名].城市.fillna(lagou_dict_30[城市名].城市.fillna(城市名))

In [16]:
for key in lagou_dict_30:
    #有城市列直接填充
    if '城市' in lagou_dict_30[key].columns:
        lagou_dict_30[key].城市.fillna(lagou_dict_30[key].城市.mode()[0], inplace=True)
    #没有城市列，添加城市列并填充（暂时可能还没有发现北京没有城市列）
#     else:
#         lagou_dict[key]['城市'] = lagou_dict_30[key].城市.mode()[0]

 # 所有城市数据合并称一个大表

In [17]:
# 新建空的DataFrame,把所有的其他数据添加到这个DataFrame中

In [18]:
df = pd.DataFrame()
for key in lagou_dict_30:
    df = df.append(lagou_dict_30[key], ignore_index=True,sort=False)
df

/var/folders/0b/023xcpqx6_s3b3dv7nxprsf00000gn/T/ipykernel_83466/2324806343.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(lagou_dict_30[key], ignore_index=True,sort=False)

,标题,城市,地点,薪资待遇,岗位要求,名称,级别,岗位技能,短评,公司地点,工位要求,公司名称,公司级别,公司短评
0,高级数据分析（对标985/211）,武汉,[白沙洲],8k-15k,8k-15k 经验1-3年 / 本科,易佰网络科技,"电商,移动互联网 / B轮 / 2000人以上",电商 算法 数据挖掘 数据分析 数据处理,“五险一金/节日福利/专业培训/全勤奖”,NaN,NaN,NaN,NaN,NaN
1,数据分析师,武汉,[洪山区],10k-20k,10k-20k 经验不限 / 不限,悦然心动,"社交,游戏 / 上市公司 / 150-500人",可视化 数据库 数据分析,“带薪出国游；千万级用户”,NaN,NaN,NaN,NaN,NaN
2,数据分析师,武汉,[东湖新技术…],10k-15k,10k-15k 经验5-10年 / 本科,盛天网络,"游戏,文娱丨内容 / 上市公司 / 500-2000人",数据分析 数据运营,“福利好 发展快”,NaN,NaN,NaN,NaN,NaN
3,数据分析师,武汉,[洪山区],20k-40k,20k-40k 经验3-5年 / 本科,字节跳动,文娱丨内容 / C轮 / 2000人以上,数据分析,“弹性工作，免费三餐，晋升空间，团队氛围好”,NaN,NaN,NaN,NaN,NaN
4,数据分析,武汉,[东湖新技术…],5k-10k,5k-10k 经验不限 / 大专,诸葛io,"企业服务,数据服务 / A轮 / 50-150人",大数据 企业服务 SQL,“五险一金 带薪年假 定期团建”,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1585,银行数据分析实习生,南京,NaN,5k-7k,NaN,NaN,NaN,Oracle 数据仓库 数据挖掘,NaN,[雨花台区],5k-7k 经验1年以下 / 本科,江苏谷科软件有限公司,"信息安全,金融 / 未融资 / 150-500人",“六险一金、年终奖、一年两次调薪机会”
1586,商业数据分析师,南京,NaN,10k-15k,NaN,NaN,NaN,数据分析,NaN,[宁南],10k-15k 经验3-5年 / 不限,讯实科技,数据服务 / B轮 / 15-50人,“五险一金 双休”
1587,BI数据分析产品经理,南京,NaN,10k-15k,NaN,NaN,NaN,新零售 BI 数据 数据分析,NaN,[鼓楼区],10k-15k 经验5-10年 / 本科,五星电器,"电商,消费生活 / 不需要融资 / 2000人以上",“五险一金、节假日福利”
1588,大数据分析开发工程师,南京,NaN,8k-15k,NaN,NaN,NaN,大数据 数据挖掘,NaN,[山西路],8k-15k 经验1-3年 / 本科,南京邮数通,"移动互联网,信息安全 / 不需要融资 / 15-50人","“项目奖金,带薪休年假,五险一金”"
1589,高级数据分析经理,南京,NaN,50k-80k,NaN,NaN,NaN,移动互联网,NaN,[雨花台区],50k-80k 经验5-10年 / 本科,vivo,硬件 / 未融资 / 2000人以上,"“股票期权,技术驱动,千万级用户”"

### 发现字段名称存在不一致情况，进一步处理

In [19]:
for key in lagou_dict_30:
    print(key)
    print(lagou_dict_30[key].columns)

wuhan
Index(['标题', '城市', '地点', '薪资待遇', '岗位要求', '名称', '级别', '岗位技能', '短评'], dtype='object')
shenzhen
Index(['标题', '城市', '公司地点', '薪资待遇', '工位要求', '公司名称', '公司级别', '岗位技能', '公司短评'], dtype='object')
hangzhou
Index(['标题', '城市', '公司地点', '薪资待遇', '工位要求', '公司名称', '公司级别', '岗位技能', '公司短评'], dtype='object')
guangzhou
Index(['标题', '城市', '公司地点', '薪资待遇', '工位要求', '公司名称', '公司级别', '岗位技能', '公司短评'], dtype='object')
chengdu
Index(['标题', '城市', '公司地点', '薪资待遇', '工位要求', '公司名称', '公司级别', '岗位技能', '公司短评'], dtype='object')
shanghai
Index(['标题', '城市', '公司地点', '薪资待遇', '工位要求', '公司名称', '公司级别', '岗位技能', '公司短评'], dtype='object')
beijing
Index(['标题', '公司地点', '薪资待遇', '工位要求', '公司名称', '公司级别', '岗位技能', '公司短评'], dtype='object')
nanjing
Index(['标题', '城市', '公司地点', '薪资待遇', '工位要求', '公司名称', '公司级别', '岗位技能', '公司短评'], dtype='object')

### 发现只有武汉与其他不同，修改一致

In [20]:
columns_name = {'地点':'公司地点', '岗位要求':'工位要求', '名称':'公司名称', '级别':'公司级别', '短评':'公司短评'}
# 发现只有武汉与其他不同
lagou_dict_30['wuhan'].rename(columns=columns_name, inplace=True)
lagou_dict_30['wuhan']

,标题,城市,公司地点,薪资待遇,工位要求,公司名称,公司级别,岗位技能,公司短评
0,高级数据分析（对标985/211）,武汉,[白沙洲],8k-15k,8k-15k 经验1-3年 / 本科,易佰网络科技,"电商,移动互联网 / B轮 / 2000人以上",电商 算法 数据挖掘 数据分析 数据处理,“五险一金/节日福利/专业培训/全勤奖”
1,数据分析师,武汉,[洪山区],10k-20k,10k-20k 经验不限 / 不限,悦然心动,"社交,游戏 / 上市公司 / 150-500人",可视化 数据库 数据分析,“带薪出国游；千万级用户”
2,数据分析师,武汉,[东湖新技术…],10k-15k,10k-15k 经验5-10年 / 本科,盛天网络,"游戏,文娱丨内容 / 上市公司 / 500-2000人",数据分析 数据运营,“福利好 发展快”
3,数据分析师,武汉,[洪山区],20k-40k,20k-40k 经验3-5年 / 本科,字节跳动,文娱丨内容 / C轮 / 2000人以上,数据分析,“弹性工作，免费三餐，晋升空间，团队氛围好”
4,数据分析,武汉,[东湖新技术…],5k-10k,5k-10k 经验不限 / 大专,诸葛io,"企业服务,数据服务 / A轮 / 50-150人",大数据 企业服务 SQL,“五险一金 带薪年假 定期团建”
5,数据分析专员,武汉,[流芳],6k-9k,6k-9k 经验3-5年 / 本科,天贝科技,移动互联网 / 未融资 / 150-500人,SPSS SQL 数据分析,“双休 五险”
6,数据分析师/数据产品经理,武汉,[流芳],18k-36k,18k-36k 经验5-10年 / 本科,小米,硬件 / D轮及以上 / 2000人以上,大数据,“五险一金、弹性工作、双休、团队氛围好”
7,数据分析-武汉,武汉,[东湖新技术…],15k-30k,15k-30k 经验5-10年 / 本科,深圳市丰巢科技有限公司,消费生活 / A轮 / 500-2000人,物流 移动互联网 数据分析 数据处理 数据挖掘,“扁平化管理 大平台 薪酬福利好”
8,数据分析师,武汉,[中北路],4k-7k,4k-7k 经验1-3年 / 本科,长江云新媒体集团,"移动互联网,数据服务 / 未融资 / 150-500人",数据分析 数据运营,“五险一金，饭补，交通费，周末双休”
9,数据分析师,武汉,[关山],8k-12k,8k-12k 经验3-5年 / 本科,斗鱼直播,文娱丨内容 / D轮及以上 / 2000人以上,分析,“下午茶；五险一金；弹性工作；前景好；”
10,资深数据分析师,武汉,[硚口区],15k-25k,15k-25k 经验3-5年 / 本科,Today今天连锁便利,消费生活 / B轮 / 500-2000人,新零售 电商 数据分析 数据挖掘 数据仓库,“平台大 发展快 不打卡”
11,数据分析师,武汉,[流芳],5k-8k,5k-8k 经验1-3年 / 大专,去哪儿网,旅游 / 不需要融资 / 2000人以上,电商 数据分析,“弹性时间 周末双休 五险一金”
12,数据分析师,武汉,[光谷],5k-8k,5k-8k 经验1-3年 / 大专,小红书,消费生活 / D轮及以上 / 500-2000人,移动互联网 数据分析,“六险一金 周末双休 13薪 定期体检等”
13,数据分析师,武汉,[珞南],10k-18k,10k-18k 经验1-3年 / 本科,跟谁学,"移动互联网,教育 / 上市公司 / 2000人以上",移动互联网 教育 数据分析 SQL 数据库,“周末双休、六险一金、带薪年假、员工旅游”
14,数据分析师助理,武汉,[珞狮南路],4k-5k,4k-5k 经验不限 / 大专,福韵数据服务有限公司,"移动互联网,数据服务 / A轮 / 150-500人",信息安全 大数据 数据分析 SQL SPSS 数据库,“助理-初一级-初二级-中一级等上升平台”
15,数据分析主管,武汉,[江夏区],15k-20k,15k-20k 经验5-10年 / 本科,盛天网络,"游戏,文娱丨内容 / 上市公司 / 500-2000人",电商 可视化 BI 数据分析 数据运营,“福利好 发展快”
16,数据分析经理（光谷）,武汉,[东湖新技术…],15k-30k,15k-30k 经验3-5年 / 本科,字节跳动,文娱丨内容 / C轮 / 2000人以上,数据分析,“六险一金，餐补，租房补贴，带薪休假”
17,资深数据分析师,武汉,[东湖新技术…],10k-20k,10k-20k 经验5-10年 / 本科,途虎养车网,汽车丨出行 / D轮及以上 / 2000人以上,大数据 BI 可视化 数据分析,"“一年多次调,优秀团队,地铁周边”"
18,数据分析主管,武汉,[丁字桥],8k-12k,8k-12k 经验3-5年 / 大专,时时同云科技（成都）有限责任公司,"移动互联网,消费生活 / C轮 / 2000人以上",本地生活 数据分析 数据处理,“六险一金 阿里背景”
19,数据分析师(J10441),武汉,[关山],15k-30k,15k-30k 经验不限 / 硕士,百分点,数据服务 / D轮及以上 / 500-2000人,数据分析,“技术大牛，福利齐全”
20,高级数据分析师,武汉,[流芳],NaN,12k-20k 经验5-10年 / 本科,优品财富管理有限公司,金融 / 未融资 / 500-2000人,移动互联网 SQLServer 数据仓库,"“BAT团队,团队氛围好,晋升空间大”"
21,高级数据分析师,武汉,[珞狮南路],10k-20k,10k-20k 经验3-5年 / 不限,福韵数据服务有限公司,"移动互联网,数据服务 / A轮 / 150-500人",数据分析 数据挖掘 SQLServer MySQL,“五险一金，年终奖，培训”
22,高级数据分析师,武汉,[东亭],10k-15k,10k-15k 经验3-5年 / 本科,中国婚博会,其他 / 不需要融资 / 500-2000人,数据仓库 数据分析 数据挖掘,“五险一金 弹性工作 双休”
23,数据分析（校招/实习）,武汉,[东湖新技术…],NaN,4k-8k 经验应届毕业生 / 本科,微派,社交 / B轮 / 50-150人,数据分析,"“发展空间大,大牛带”"
24,高级业务数据分析师,武汉,[光谷],10k-15k,10k-15k 经验3-5年 / 本科,小红书,消费生活 / D轮及以上 / 500-2000人,数据分析,“六险一金 周末双休 13薪 定期体检等”
25,数据分析工程师,武汉,[东湖新技术…],12k-18k,12k-18k 经验应届毕业生 / 本科,极验,"信息安全,数据服务 / B轮 / 50-150人",大数据 数据挖掘 数据分析,"“有挑战性,技术先驱,大牛队友”"
26,亚马逊数据分析,武汉,[白沙洲],8k-13k,8k-13k 经验不限 / 本科,易佰网络科技,"电商,移动互联网 / B轮 / 2000人以上",电商 数据分析,“五险一金下午茶全勤带薪年假法定假等”
27,数据分析师,武汉,[洪山区],NaN,5k-10k 经验1-3年 / 本科,掌游科技,"移动互联网,游戏 / 上市公司 / 150-500人",数据分析 数据运营,"“流水过亿,扁平管理,专业团队,定期培训”"
28,数据分析经理,武汉,[中北路],12k-20k,12k-20k 经验5-10年 / 本科,安居客,"移动互联网,消费生活 / 上市公司 / 500-2000人",策略运营 数据分析,“五险一金、年终奖、超长过年假”
29,数据分析工程师,武汉,[关山],10k-15k,10k-15k 经验3-5年 / 本科,海康威视武汉研发中心,"信息安全,数据服务 / 上市公司 / 2000人以上",大数据,“六险一金；大平台”
30,商业化-高级数据分析师,武汉,[洪山区],8k-16k,经验3-5年 / 本科,字节跳动,文娱丨内容 / C轮 / 2000人以上,项目管理,“六险一金，餐补，带薪休假，扁平管理”
31,数据分析产品经理,武汉,[珞狮南路],8k-15k,8k-15k 经验1-3年 / 本科,福韵数据服务有限公司,"移动互联网,数据服务 / A轮 / 150-500人",大数据 产品设计 需求分析 数据分析 项目管理,“五险一金，年终奖，培训”
32,数据分析师,武汉,[东湖新技术…],8k-10k,8k-10k 经验应届毕业生 / 硕士,看电影了没,"移动互联网,文娱丨内容 / 不需要融资 / 15-50人",视频 SPSS 数据分析 SQL,“粉丝多 ；福利多；前景好；不官僚”
33,资深数据分析工程师\数据分析专家,武汉,[洪山区],15k-30k,15k-30k 经验5-10年 / 本科,斗鱼直播,文娱丨内容 / D轮及以上 / 2000人以上,大数据 数据挖掘 数据分析,"“行业发展快,公司发展好”"
34,数据分析师,武汉,[江夏区],7k-14k,7k-14k 经验3-5年,烽火科技·虹旭信息技术有限公司,"信息安全,数据服务 / 不需要融资 / 150-500人",数据分析 数据运营,"“班车,提供食宿,奖金,薪酬增长,沟通畅通”"
35,数据分析师,武汉,[中北路],8k-15k,8k-15k 经验5-10年 / 本科,安居客,"移动互联网,消费生活 / 上市公司 / 500-2000人",数据运营 数据分析,“五险一金、年终奖、超长过年假”
36,安全数据分析工程师,武汉,[东湖新技术…],10k-14k,10k-14k 经验1-3年 / 本科,绿盟科技,信息安全 / 上市公司 / 500-2000人,信息安全 数据分析,“五险一金；绩效奖金；股票期权”
37,数据分析工程师,武汉,[武昌区],9k-15k,9k-15k 经验不限 / 本科,天风证券,金融 / 不需要融资 / 2000人以上,证券/期货 MySQL Oracle Java SQLServer,"“精英团队,发展空间大,福利待遇好”"
38,数据分析专员（英语六级）,武汉,[东湖新技术…],4k-6k,4k-6k 经验不限 / 本科,普利菲特,电商 / 未融资 / 15-50人,大数据 广告营销 数据分析 数据运营,“弹性工作，五险一金”
39,数据分析主管/经理,武汉,[关山],20k-30k,20k-30k 经验5-10年 / 本科,慧控科技,移动互联网 / 不需要融资 / 50-150人,数据分析,“五险一金 三个月年终奖”
40,数据分析算法工程师,武汉,NaN,10k-20k,10k-20k 经验3-5年 / 硕士,三藏科技,软件开发 / 未融资 / 15-50人,建模 机器学习 算法,“办公环境优、资深大佬指导、领导超Nice”
41,风控数据分析师,武汉,[流芳],10k-18k,10k-18k 经验3-5年 / 本科,天贝科技,移动互联网 / 未融资 / 150-500人,大数据 移动互联网 可视化 数据分析 商业,“发展空间大高薪高福利出国游周末双休”
42,商业化-高级数据分析师,武汉,[洪山区],6k-12k,6k-12k 经验3-5年 / 本科,字节跳动,文娱丨内容 / C轮 / 2000人以上,移动互联网 数据分析 行业分析 市场竞争分析,“六险一金、团队氛围好、餐补、扁平化管理”
43,商业化-数据分析支持,武汉,[洪山区],5k-10k,5k-10k 经验1-3年 / 本科,字节跳动,文娱丨内容 / C轮 / 2000人以上,广告营销 技术支持,“六险一金、团队氛围好、带薪休假、晋升空间”
44,高级数据分析产品经理,武汉,[鲁巷],25k-40k,25k-40k 经验5-10年 / 本科,斗鱼直播,文娱丨内容 / D轮及以上 / 2000人以上,直播 数据分析,“发展空间大，福利齐全”

### 发现北京没有城市列，添加该列, 并填充城市名

In [29]:
# 发现北京没有城市列，添加该列
lagou_dict_30['beijing'][['城市']] = '北京'
lagou_dict_30['beijing']

,标题,公司地点,薪资待遇,工位要求,公司名称,公司级别,岗位技能,公司短评,城市
0,数据分析师,[东城区],15k-25k,15k-25k 经验3-5年 / 本科,玩吧,社交 / B轮 / 150-500人,数据分析 SPSS SQL,"“七险一金,免费午餐,弹性不打卡,季度旅游”",北京
1,数据分析师,[大望路],10k-20k,10k-20k 经验不限 / 本科,和信集团,金融 / 不需要融资 / 2000人以上,数据分析,“五险一金、周末双休”,北京
2,数据分析师,[望京],15k-25k,15k-25k 经验3-5年 / 本科,水滴互助,"移动互联网,医疗丨健康 / B轮 / 500-2000人",数据分析 MySQL Hive,"“年底双薪,股票期权,扁平管理,晋升快”",北京
3,数据分析,[西北旺],15k-30k,15k-30k 经验3-5年 / 本科,易企秀,移动互联网 / B轮 / 150-500人,数据运营 SPSS SQL,“七险一金、零食水果、带薪年假、年度旅游等”,北京
4,数据分析师,[东城区],15k-20k,15k-20k 经验3-5年 / 大专,齐聚科技（原呱呱视频）,"移动互联网,游戏 / C轮 / 150-500人",游戏 社交 SQL 数据分析 商业,"“五险一金,弹性工作,餐补年终奖,节日福利”",北京
...,...,...,...,...,...,...,...,...,...
445,课程数据分析专员,[朝阳区],6k-9k,6k-9k 经验1年以下 / 本科,笔记侠,移动互联网 / A轮 / 15-50人,互联网金融 教育 运营 数据分析 效果跟踪,“公司资源，发展前景，加班少”,北京
446,数据分析师（数据产品经理）,[北京大学],25k-35k,25k-35k 经验3-5年 / 本科,新浪微博,文娱丨内容 / 上市公司 / 2000人以上,大数据 数据挖掘 数据分析,"“带薪年假,大平台福利,六险一金,出境游”",北京
447,数据分析岗,[广内大街],8k-15k,8k-15k 经验3-5年 / 本科,国家电网全资子公司北京汇通金财,"电商,金融 / 不需要融资 / 500-2000人",数据分析,“福利待遇 发展前景”,北京
448,产品数据分析专员,[清河],8k-15k,8k-15k 经验1-3年 / 本科,小米,硬件 / D轮及以上 / 2000人以上,其他,“大牛团队”,北京
449,数据分析挖掘,[朝外],30k-50k,30k-50k 经验3-5年 / 本科,索信达数据,人工智能 / 上市公司 / 150-500人,大数据 银行 数据挖掘 数据分析,“七险一金，不加班；晋升快速，涨知识；”,北京

### 修改城市列的位置

In [32]:
# 插在第一列后面， 此方法适合已经有该列了,因为insert第二个参数是原来的列名

col = lagou_dict_30['beijing'].城市

lagou_dict_30['beijing'] = lagou_dict_30['beijing'].drop('城市', axis=1)
lagou_dict_30['beijing'] 

lagou_dict_30['beijing'].insert(1, '城市', col)

lagou_dict_30['beijing']

,标题,公司地点,薪资待遇,工位要求,公司名称,公司级别,岗位技能,公司短评
0,数据分析师,[东城区],15k-25k,15k-25k 经验3-5年 / 本科,玩吧,社交 / B轮 / 150-500人,数据分析 SPSS SQL,"“七险一金,免费午餐,弹性不打卡,季度旅游”"
1,数据分析师,[大望路],10k-20k,10k-20k 经验不限 / 本科,和信集团,金融 / 不需要融资 / 2000人以上,数据分析,“五险一金、周末双休”
2,数据分析师,[望京],15k-25k,15k-25k 经验3-5年 / 本科,水滴互助,"移动互联网,医疗丨健康 / B轮 / 500-2000人",数据分析 MySQL Hive,"“年底双薪,股票期权,扁平管理,晋升快”"
3,数据分析,[西北旺],15k-30k,15k-30k 经验3-5年 / 本科,易企秀,移动互联网 / B轮 / 150-500人,数据运营 SPSS SQL,“七险一金、零食水果、带薪年假、年度旅游等”
4,数据分析师,[东城区],15k-20k,15k-20k 经验3-5年 / 大专,齐聚科技（原呱呱视频）,"移动互联网,游戏 / C轮 / 150-500人",游戏 社交 SQL 数据分析 商业,"“五险一金,弹性工作,餐补年终奖,节日福利”"
...,...,...,...,...,...,...,...,...
445,课程数据分析专员,[朝阳区],6k-9k,6k-9k 经验1年以下 / 本科,笔记侠,移动互联网 / A轮 / 15-50人,互联网金融 教育 运营 数据分析 效果跟踪,“公司资源，发展前景，加班少”
446,数据分析师（数据产品经理）,[北京大学],25k-35k,25k-35k 经验3-5年 / 本科,新浪微博,文娱丨内容 / 上市公司 / 2000人以上,大数据 数据挖掘 数据分析,"“带薪年假,大平台福利,六险一金,出境游”"
447,数据分析岗,[广内大街],8k-15k,8k-15k 经验3-5年 / 本科,国家电网全资子公司北京汇通金财,"电商,金融 / 不需要融资 / 500-2000人",数据分析,“福利待遇 发展前景”
448,产品数据分析专员,[清河],8k-15k,8k-15k 经验1-3年 / 本科,小米,硬件 / D轮及以上 / 2000人以上,其他,“大牛团队”
449,数据分析挖掘,[朝外],30k-50k,30k-50k 经验3-5年 / 本科,索信达数据,人工智能 / 上市公司 / 150-500人,大数据 银行 数据挖掘 数据分析,“七险一金，不加班；晋升快速，涨知识；”

,标题,城市,公司地点,薪资待遇,工位要求,公司名称,公司级别,岗位技能,公司短评
0,数据分析师,北京,[东城区],15k-25k,15k-25k 经验3-5年 / 本科,玩吧,社交 / B轮 / 150-500人,数据分析 SPSS SQL,"“七险一金,免费午餐,弹性不打卡,季度旅游”"
1,数据分析师,北京,[大望路],10k-20k,10k-20k 经验不限 / 本科,和信集团,金融 / 不需要融资 / 2000人以上,数据分析,“五险一金、周末双休”
2,数据分析师,北京,[望京],15k-25k,15k-25k 经验3-5年 / 本科,水滴互助,"移动互联网,医疗丨健康 / B轮 / 500-2000人",数据分析 MySQL Hive,"“年底双薪,股票期权,扁平管理,晋升快”"
3,数据分析,北京,[西北旺],15k-30k,15k-30k 经验3-5年 / 本科,易企秀,移动互联网 / B轮 / 150-500人,数据运营 SPSS SQL,“七险一金、零食水果、带薪年假、年度旅游等”
4,数据分析师,北京,[东城区],15k-20k,15k-20k 经验3-5年 / 大专,齐聚科技（原呱呱视频）,"移动互联网,游戏 / C轮 / 150-500人",游戏 社交 SQL 数据分析 商业,"“五险一金,弹性工作,餐补年终奖,节日福利”"
...,...,...,...,...,...,...,...,...,...
445,课程数据分析专员,北京,[朝阳区],6k-9k,6k-9k 经验1年以下 / 本科,笔记侠,移动互联网 / A轮 / 15-50人,互联网金融 教育 运营 数据分析 效果跟踪,“公司资源，发展前景，加班少”
446,数据分析师（数据产品经理）,北京,[北京大学],25k-35k,25k-35k 经验3-5年 / 本科,新浪微博,文娱丨内容 / 上市公司 / 2000人以上,大数据 数据挖掘 数据分析,"“带薪年假,大平台福利,六险一金,出境游”"
447,数据分析岗,北京,[广内大街],8k-15k,8k-15k 经验3-5年 / 本科,国家电网全资子公司北京汇通金财,"电商,金融 / 不需要融资 / 500-2000人",数据分析,“福利待遇 发展前景”
448,产品数据分析专员,北京,[清河],8k-15k,8k-15k 经验1-3年 / 本科,小米,硬件 / D轮及以上 / 2000人以上,其他,“大牛团队”
449,数据分析挖掘,北京,[朝外],30k-50k,30k-50k 经验3-5年 / 本科,索信达数据,人工智能 / 上市公司 / 150-500人,大数据 银行 数据挖掘 数据分析,“七险一金，不加班；晋升快速，涨知识；”

In [ ]:
# 继续合并
df = pd.DataFrame()
for key in lagou_dict_30:
    df = df.append(lagou_dict_30[key], ignore_index=True,sort=False)
df

### 了解数据

In [ ]:
df[df.isnull().sum(axis=1)>0]

In [ ]:
df.describe()

# 进一步处理数据

   ## 去掉公司地点中的[ ]

In [ ]:
# 去掉公司地点中的[]
df['公司地点'] = df.公司地点.str.replace(']', '').str.replace('[', '')

In [ ]:
df

In [ ]:
df_copy_2520 = df.copy()

## 把工位要求拆分成3列(数据有问题，有些工位要求的列没有薪资)

In [ ]:
t = df[~(df.工位要求.str.contains('k') | df.工位要求.str.contains('K'))] #这些工位要求列没有薪资,加上
t

In [ ]:
df.loc[t.index, '工位要求'] = ['8k-16k ', '6k-8k ', '6k-9k '] + df.loc[t.index, '工位要求']  # 拼接成功
df.iloc[1575:]

In [ ]:
# 把工位要求拆分成三列
df[['薪资', '经验要求', '临时', '学历']] = df.工位要求.str.split(' ', expand = True)

In [ ]:
df

In [ ]:
# df.iloc[1570:]

### 去掉重复列

In [ ]:
#去掉重复列
df.drop(columns=['薪资待遇', '工位要求', '临时'], inplace = True) 
df

## 薪资列处理，拆分成最大值和最小值

In [ ]:
salary = df.薪资.str.replace('k', '000').str.replace('K', '000')
salary

In [ ]:
df[['最高薪资', '最低薪资']] = salary.str.split('-', expand = True)

In [ ]:
# 将薪资改成整数型
df.最高薪资 = df.最高薪资.astype('int')
df.最低薪资 = df.最低薪资.astype('int')
df

In [ ]:
df['平均薪资'] = (df.最高薪资 + df.最低薪资) // 2

In [ ]:
df

In [ ]:
df.pop('薪资')

In [ ]:
df

## 公司级别拆分

In [ ]:
df[['公司类型', '融资阶段', '公司规模']] = df.公司级别.str.split('/', expand = True)
df

In [ ]:
df.pop('公司级别')

In [ ]:
df

In [ ]:
df.公司短评 = df.公司短评.str.replace('“', '').str.replace('”', '')

In [ ]:
df

In [ ]:
# 调整列顺序
df = df[['标题','城市','公司名称','公司地点','公司类型',
   '融资阶段','公司规模','经验要求','学历',
   '最低薪资','最高薪资','平均薪资',
   '岗位技能','公司短评']]
df

# 数据统计分析

## 查看数据分布情况

### 柱状图

In [ ]:

x = df.城市.value_counts().index
print(x)
y = df.城市.value_counts()
print(y)

In [ ]:
#mac电脑正常显示中文
plt.rcParams['font.family'] = ['Arial Unicode MS']

In [ ]:
plt.figure(figsize=(10,7))
plt.bar(x, y)
plt.title('城市对应的职位个数')

In [ ]:
# 封装一个画bar图的函数

def bar(column):
    x = df[column].value_counts().index
    y = df[column].value_counts()
    plt.figure(figsize=(10,7))
    plt.bar(x, y)

bar('公司规模')

In [ ]:
bar('学历')

In [ ]:
bar('经验要求')

In [ ]:
# bar('公司地点')

### 曲线图

In [ ]:
# 薪资的密度曲线/直方图
df[['最低薪资','平均薪资','最高薪资']].plot(kind='kde')
plt.xlim(-10000,100000);

### 直方图

In [ ]:
plt.hist(df.平均薪资, bins=[0, 5000, 10000, 15000, 20000, 25000, 30000, 35000, 
                        40000, 45000,50000, 55000,60000, 100000])

## 分组统计

不同城市的薪资

In [ ]:
df.groupby('城市').mean().sort_values(by= '平均薪资',ascending = False)

In [ ]:
df.groupby('城市')['平均薪资'].agg(['max', 'min', 'median', 'mean'])

### 过滤薪资大于5万的岗位

In [ ]:
df[df['平均薪资']>=50000]
df[df['平均薪资']>=50000].count()

### 判断结果是否有重复

In [ ]:
df.duplicated().value_counts()  #  True的部分就是重复数据

### 去掉重复数据

In [ ]:
# 去掉重复数据,少了4行数据
df[df['平均薪资']>=50000].drop_duplicates(subset=['标题', '公司名称', '岗位技能']) # 根据这些列进行去重，或者不写也可
df[df['平均薪资']>=50000].drop_duplicates().count()

In [ ]:
# 封装函数
def salary(column):
    return df.groupby(column).mean().sort_values(by= '平均薪资',ascending = False)
salary('融资阶段')

In [ ]:
salary('公司规模')# 发现公司越大，获得高薪的可能性越大

In [ ]:
salary('经验要求')  # 经验越多，薪资越高

In [ ]:
tt = salary('学历')  # 博士到研究生的平均薪资断崖式下降
tt
x = list(tt.index)
x
y = list(tt.最低薪资)
y

### 柱状图

In [ ]:
plt.barh(x,y)  # x,y 都要是list
plt.title('学历对平均薪资的影响')